# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.storedfile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='user_username_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('STUDENT', 'STAFF', 'ADMIN', 'SUPERADMIN'))), name='user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False)), name='user_never_superuser'),
        ),
        migrations.AddIndex(
            model_name='mfaenrollmentcode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_mf_user_id_3b18bf_idx'),
        ),
        migrations.AddIndex(
            model_name='mfarecoverycode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_mf_user_id_0737c3_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_pa_user_id_ba1dfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordresetcode',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0), ('attempts__lte', 5)), name='reset_attempts_range'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['program'], name='accounts_st_program_64aeab_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['academic_status'], name='accounts_st_academi_f2d7d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('year_of_study__gte', 1), ('year_of_study__lte', 8)), name='student_year_range'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('current_semester_number__gte', 1), ('current_semester_number__lte', 3)), name='student_semester_range'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('academic_status__in', ['ACTIVE', 'PROBATION', 'SUSPENDED', 'DEFERRED', 'GRADUATED', 'WITHDRAWN'])), name='student_academic_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('disciplinary_status__in', ['CLEAR', 'UNDER_REVIEW', 'SANCTIONED'])), name='student_disciplinary_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gender', ''), ('gender__in', ['FEMALE', 'MALE', 'OTHER']), _connector='OR'), name='student_gender_valid'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'revoked_at'], name='accounts_tr_user_id_081ab0_idx'),
        ),
    ]
