# Generated by Django 5.2.18 on 2026-10-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_units",
                to="accounts.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="unitprerequisite",
            name="prerequisite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_for_links",
                to="academics.unit",
            ),
        ),
        migrations.AddField(
            model_name="unitprerequisite",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prerequisite_links",
                to="academics.unit",
            ),
        ),
        migrations.AddField(
            model_name="unitregistration",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unit_registrations",
                to="academics.semester",
            ),
        ),
        migrations.AddField(
            model_name="unitregistration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_registrations",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="unitregistration",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="academics.unit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "semester_number")},
        ),
        migrations.AlterUniqueTogether(
            name="unitprerequisite",
            unique_together={("unit", "prerequisite")},
        ),
        migrations.AddConstraint(
            model_name="unitregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "REGISTERED")),
                fields=("student", "unit", "semester"),
                name="unique_active_registration_per_student_unit_semester",
            ),
        ),
    ]
