# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoffering',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.unit'),
        ),
        migrations.AddField(
            model_name='unitprerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_for_links', to='academics.unit'),
        ),
        migrations.AddField(
            model_name='unitprerequisite',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='academics.unit'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.unitoffering'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Set only for an administrative override; null = the student registered themselves.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.unit'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('award_level__in', ['CERTIFICATE', 'DIPLOMA', 'BACHELOR', 'MASTER', 'DOCTORATE'])), name='program_award_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('duration_years__gte', 1), ('duration_years__lte', 8)), name='program_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('max_credits_per_semester__gte', 1), ('max_credits_per_semester__lte', 60)), name='program_max_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('min_credits_per_semester__gte', 0), ('min_credits_per_semester__lte', models.F('max_credits_per_semester'))), name='program_min_credits_le_max'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='semester_unique_number_per_year'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 3)), name='semester_number_range'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='semester_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('registration_opens_at__lt', models.F('registration_closes_at'))), name='semester_registration_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='one_current_semester'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('credit_hours__gte', 1), ('credit_hours__lte', 10)), name='unit_credit_range'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 8)), name='unit_level_range'),
        ),
        migrations.AddIndex(
            model_name='unitoffering',
            index=models.Index(fields=['semester', 'status'], name='academics_u_semeste_b25e0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitoffering',
            constraint=models.UniqueConstraint(fields=('unit', 'semester', 'section'), name='offering_unique_section'),
        ),
        migrations.AddConstraint(
            model_name='unitoffering',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='offering_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitoffering',
            constraint=models.CheckConstraint(condition=models.Q(('min_year__gte', 1), ('min_year__lte', 8)), name='offering_min_year_range'),
        ),
        migrations.AddConstraint(
            model_name='unitoffering',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'OPEN', 'CLOSED', 'CANCELLED'])), name='offering_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='unitprerequisite',
            constraint=models.UniqueConstraint(fields=('unit', 'prerequisite'), name='prerequisite_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='unitprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('unit', models.F('prerequisite')), _negated=True), name='prerequisite_not_self'),
        ),
        migrations.AddIndex(
            model_name='unitregistration',
            index=models.Index(fields=['offering', 'status'], name='academics_u_offerin_cbc48c_idx'),
        ),
        migrations.AddIndex(
            model_name='unitregistration',
            index=models.Index(fields=['student', 'status'], name='academics_u_student_3251dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('REGISTERED', 'COMPLETED'))), fields=('student', 'unit', 'semester'), name='registration_one_live_per_unit_semester'),
        ),
        migrations.AddConstraint(
            model_name='unitregistration',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['REGISTERED', 'DROPPED', 'COMPLETED', 'FAILED', 'WITHDRAWN'])), name='registration_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='unitregistration',
            constraint=models.CheckConstraint(condition=models.Q(('grade', ''), ('grade__in', ['A', 'B', 'C', 'D', 'E', 'I']), _connector='OR'), name='registration_grade_valid'),
        ),
        migrations.AddConstraint(
            model_name='unitregistration',
            constraint=models.CheckConstraint(condition=models.Q(('grade_points__isnull', True), models.Q(('grade_points__gte', 0), ('grade_points__lte', 4)), _connector='OR'), name='registration_grade_points_range'),
        ),
    ]
