# Generated by Django 5.2.18 on 2026-10-07 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("campus", models.CharField(default="Main Campus", max_length=100)),
                ("capacity", models.PositiveIntegerField(default=50)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("LECTURE_HALL", "Lecture Hall"),
                            ("LABORATORY", "Science/Computer Laboratory"),
                            ("SEMINAR_ROOM", "Seminar Room"),
                            ("TUTORIAL_ROOM", "Tutorial Room"),
                        ],
                        default="LECTURE_HALL",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["building", "code"],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture"),
                            ("TUTORIAL", "Tutorial"),
                            ("LAB", "Laboratory Session"),
                            ("WORKSHOP", "Workshop"),
                        ],
                        default="LECTURE",
                        max_length=20,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_slots",
                        to="timetable.classroom",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lectures",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.semester",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["semester", "day_of_week", "start_time"],
                        name="timetable_t_semeste_c78b4e_idx",
                    ),
                    models.Index(
                        fields=["classroom", "day_of_week"],
                        name="timetable_t_classro_d64ca0_idx",
                    ),
                ],
            },
        ),
    ]
