# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_of_study', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('label', models.CharField(max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='academics.program')),
            ],
            options={
                'ordering': ['program__code', 'year_of_study', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('campus', models.CharField(default='Main Campus', max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('venue_type', models.CharField(default='LECTURE_HALL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='venue_capacity_positive')],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('TUTORIAL', 'Tutorial'), ('LAB', 'Lab'), ('WORKSHOP', 'Workshop'), ('EXAM', 'Exam')], default='LECTURE', max_length=10)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='accounts.staffprofile')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.unitoffering')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.semester')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetable.studentgroup')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetable.venue')),
            ],
            options={
                'verbose_name_plural': 'timetable entries',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('program', 'year_of_study', 'label'), name='student_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('year_of_study__gte', 1), ('year_of_study__lte', 8)), name='student_group_year_range'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['venue', 'day_of_week'], name='timetable_t_venue_i_564515_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['offering'], name='timetable_t_offerin_210571_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='timetable_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='timetable_day_range'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('class_type__in', ['LECTURE', 'TUTORIAL', 'LAB', 'WORKSHOP', 'EXAM'])), name='timetable_class_type_valid'),
        ),
    ]
