# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_students', 'Create and edit student records and institutional fields'), ('manage_staff', 'Create and edit staff profiles'), ('manage_academics', 'Manage faculties, departments, programs, academic years and semesters'), ('manage_units', 'Manage units, offerings, prerequisites and lecturer assignment'), ('record_grades', 'Record grades for offerings the lecturer teaches'), ('manage_grades', 'Record or amend any grade'), ('manage_timetable', 'Create and edit timetable entries'), ('manage_hostels', 'Manage hostels, rooms, beds, booking windows and allocations'), ('manage_request_config', 'Manage request categories, routing and approval requirements'), ('review_requests', 'Triage, assign and respond to requests in scope'), ('review_all_requests', 'Review requests in every department'), ('approve_requests', 'Approve or reject approval-type requests'), ('approve_transfers', 'Approve or reject transfer requests'), ('execute_transfers', 'Apply an approved transfer to the academic record'), ('manage_clubs', 'Manage clubs, officers and memberships'), ('publish_announcements', 'Publish announcements'), ('manage_user_accounts', 'Activate, deactivate, reset password or MFA for student/staff accounts'), ('view_audit_logs', 'Read audit logs and security events'), ('view_statistics', 'View admin dashboard statistics'), ('manage_roles', 'Change roles, groups and capabilities; manage admin accounts'), ('manage_system_settings', 'Manage security and system configuration'), ('manage_backups', 'Trigger and verify backups')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AuditSeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('stream', models.CharField(choices=[('AUDIT', 'Audit log'), ('SECURITY', 'Security events'), ('REQUEST_HISTORY', 'Request status history')], max_length=20)),
                ('from_seq', models.BigIntegerField()),
                ('to_seq', models.BigIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('previous_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stream', 'from_seq'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stream__in', ['AUDIT', 'SECURITY', 'REQUEST_HISTORY'])), name='auditseal_stream_valid'), models.CheckConstraint(condition=models.Q(('from_seq__lte', models.F('to_seq'))), name='auditseal_range_ordered'), models.UniqueConstraint(fields=('stream', 'from_seq'), name='auditseal_unique_start')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_identifier', models.CharField(max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'), models.Index(fields=['actor', 'timestamp'], name='core_auditl_actor_i_19c60f_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['SUCCESS', 'DENIED', 'FAILED'])), name='auditlog_outcome_valid')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGOUT', 'Logout'), ('THROTTLED', 'Throttled / locked out'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('PASSWORD_CHANGED', 'Password changed'), ('MFA_CHALLENGE', 'MFA challenge presented'), ('MFA_SUCCESS', 'MFA success'), ('MFA_FAILURE', 'MFA failure'), ('MFA_ENROLLED', 'MFA device enrolled'), ('MFA_RESET', 'MFA reset'), ('MFA_RECOVERY_USED', 'MFA recovery code used'), ('PERMISSION_DENIED', 'Permission denied'), ('RATE_LIMITED', 'Rate limited'), ('UPLOAD_REJECTED', 'Upload rejected'), ('ROLE_CHANGED', 'Role or capability changed'), ('SESSION_EXPIRED', 'Session expired')], max_length=40)),
                ('identifier_hash', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_securi_event_t_72c930_idx'), models.Index(fields=['user', 'timestamp'], name='core_securi_user_id_8e89f8_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_securi_ip_addr_a2d011_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'THROTTLED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'PASSWORD_CHANGED', 'MFA_CHALLENGE', 'MFA_SUCCESS', 'MFA_FAILURE', 'MFA_ENROLLED', 'MFA_RESET', 'MFA_RECOVERY_USED', 'PERMISSION_DENIED', 'RATE_LIMITED', 'UPLOAD_REJECTED', 'ROLE_CHANGED', 'SESSION_EXPIRED'])), name='securityevent_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_name', models.CharField(max_length=100, unique=True)),
                ('original_name', models.CharField(max_length=150)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('PROFILE_PHOTO', 'Profile photo'), ('REQUEST_ATTACHMENT', 'Request attachment'), ('ANNOUNCEMENT_ATTACHMENT', 'Announcement attachment')], max_length=30)),
                ('scan_status', models.CharField(choices=[('NOT_SCANNED', 'Not scanned'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected')], default='NOT_SCANNED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='storedfile_size_positive'), models.CheckConstraint(condition=models.Q(('purpose__in', ['PROFILE_PHOTO', 'REQUEST_ATTACHMENT', 'ANNOUNCEMENT_ATTACHMENT'])), name='storedfile_purpose_valid'), models.CheckConstraint(condition=models.Q(('scan_status__in', ['NOT_SCANNED', 'CLEAN', 'INFECTED'])), name='storedfile_scan_status_valid')],
            },
        ),
    ]
