# Generated by Django 5.2.18 on 2026-10-07 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_identifier",
                    models.CharField(
                        help_text="Cached username/email or 'SYSTEM'", max_length=150
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=50)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_model", models.CharField(db_index=True, max_length=100)),
                ("target_id", models.CharField(db_index=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="Stores previous_state and new_state"
                    ),
                ),
                ("status", models.CharField(default="SUCCESS", max_length=30)),
                ("details", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="core_auditl_actor_i_19c60f_idx",
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="core_auditl_target__315580_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_auditl_action_096de0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("LOGOUT", "Logout"),
                            ("LOCKOUT", "Account Lockout Triggered"),
                            ("PASSWORD_RESET", "Password Reset Requested"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("MFA_CHALLENGE", "MFA Challenge Presented"),
                            ("MFA_SUCCESS", "MFA Verification Succeeded"),
                            ("MFA_FAILURE", "MFA Verification Failed"),
                            (
                                "PERMISSION_DENIED",
                                "Permission Denied / Authorization Failure",
                            ),
                            (
                                "IDOR_ATTEMPT",
                                "Potential Insecure Direct Object Reference Attempt",
                            ),
                            ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                            (
                                "SUSPICIOUS_UPLOAD",
                                "Malicious or Disallowed File Upload Attempted",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("username_attempted", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="core_securi_event_t_014c2d_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="core_securi_ip_addr_3579f4_idx",
                    ),
                ],
            },
        ),
    ]
