# Generated by Django 5.2.18 on 2026-10-08 03:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capability_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('ok', models.BooleanField()),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job', '-started_at'], name='maintenancerun_job_started')],
            },
        ),
    ]
