# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNumberCounter',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_capability', models.CharField(choices=[('approve_requests', 'approve_requests'), ('approve_transfers', 'approve_transfers')], default='approve_requests', max_length=30)),
                ('allows_attachments', models.BooleanField(default=True)),
                ('max_attachments', models.PositiveSmallIntegerField(default=3)),
                ('is_transfer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_categories', to='academics.department')),
            ],
            options={
                'verbose_name_plural': 'request categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('resolution', models.TextField(blank=True, max_length=5000)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to='accounts.staffprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='student_requests.requestcategory')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='academics.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('from_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_INFORMATION', 'Needs information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='student_requests.studentrequest')),
            ],
            options={
                'ordering': ['created_at', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=5000)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Visible to the student'), ('INTERNAL', 'Staff only')], default='PUBLIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='student_requests.studentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Visible to the student'), ('INTERNAL', 'Staff only')], default='PUBLIC', max_length=10)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request_attachment', to='core.storedfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='student_requests.requestmessage')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='student_requests.studentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_type', models.CharField(choices=[('PROGRAM', 'Program transfer'), ('DEPARTMENT', 'Department transfer'), ('CAMPUS', 'Campus transfer'), ('FACULTY', 'Faculty transfer')], max_length=12)),
                ('from_campus', models.CharField(max_length=100)),
                ('to_campus', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(max_length=5000)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('from_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.program')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='student_requests.studentrequest')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('to_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.program')),
            ],
        ),
        migrations.AddConstraint(
            model_name='requestcategory',
            constraint=models.CheckConstraint(condition=models.Q(('default_priority__in', ['LOW', 'NORMAL', 'HIGH', 'URGENT'])), name='category_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='requestcategory',
            constraint=models.CheckConstraint(condition=models.Q(('approval_capability__in', ['approve_requests', 'approve_transfers'])), name='category_approval_capability_valid'),
        ),
        migrations.AddConstraint(
            model_name='requestcategory',
            constraint=models.CheckConstraint(condition=models.Q(('is_transfer', False), ('approval_capability', 'approve_transfers'), _connector='OR'), name='category_transfer_needs_transfer_approval'),
        ),
        migrations.AddConstraint(
            model_name='requestcategory',
            constraint=models.CheckConstraint(condition=models.Q(('is_transfer', False), ('requires_approval', True), _connector='OR'), name='category_transfer_requires_approval'),
        ),
        migrations.AddConstraint(
            model_name='requestcategory',
            constraint=models.CheckConstraint(condition=models.Q(('max_attachments__gte', 0), ('max_attachments__lte', 10)), name='category_max_attachments_range'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['student', 'status'], name='student_req_student_422d54_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['department', 'status'], name='student_req_departm_582815_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='student_req_assigne_325637_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['created_at'], name='student_req_created_038fe9_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'UNDER_REVIEW', 'NEEDS_INFORMATION', 'APPROVED', 'REJECTED', 'RESOLVED', 'CLOSED', 'CANCELLED'])), name='request_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='studentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'NORMAL', 'HIGH', 'URGENT'])), name='request_priority_valid'),
        ),
        migrations.AddIndex(
            model_name='requeststatuschange',
            index=models.Index(fields=['request', 'created_at'], name='student_req_request_071a0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestmessage',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['PUBLIC', 'INTERNAL'])), name='request_message_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['PUBLIC', 'INTERNAL'])), name='request_attachment_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_type__in', ['PROGRAM', 'DEPARTMENT', 'CAMPUS', 'FACULTY'])), name='transfer_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_campus', ''), ('to_department__isnull', True), ('to_program__isnull', False), ('transfer_type__in', ['PROGRAM', 'FACULTY'])), models.Q(('to_campus', ''), ('to_department__isnull', False), ('to_program__isnull', True), ('transfer_type', 'DEPARTMENT')), models.Q(('to_department__isnull', True), ('to_program__isnull', True), ('transfer_type', 'CAMPUS'), models.Q(('to_campus', ''), _negated=True)), _connector='OR'), name='transfer_target_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('executed_at__isnull', True), ('executed_by__isnull', True)), models.Q(('executed_at__isnull', False), ('executed_by__isnull', False)), _connector='OR'), name='transfer_execution_fields_together'),
        ),
    ]
