# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CLUB', 'Club'), ('SOCIETY', 'Society')], default='CLUB', max_length=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('meeting_info', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Club address, never a personal one.', max_length=254)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_clubs', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Everyone'), ('MEMBERS', 'Members only')], default='PUBLIC', max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='PENDING', max_length=10)),
                ('position', models.CharField(choices=[('MEMBER', 'Member'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('VICE_CHAIR', 'Vice chair'), ('CHAIR', 'Chair')], default='MEMBER', max_length=12)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='clubs.club')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_memberships', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['club__name', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['CLUB', 'SOCIETY'])), name='club_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='clubevent',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='club_event_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='clubevent',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['PUBLIC', 'MEMBERS'])), name='club_event_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'LEFT', 'REMOVED'])), name='membership_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.CheckConstraint(condition=models.Q(('position__in', ['MEMBER', 'SECRETARY', 'TREASURER', 'VICE_CHAIR', 'CHAIR'])), name='membership_position_valid'),
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('club', 'student'), name='membership_one_open_per_club'),
        ),
    ]
