# Generated by Django 5.2.18 on 2026-10-07 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "gender_policy",
                    models.CharField(
                        choices=[
                            ("MALE", "Male Only"),
                            ("FEMALE", "Female Only"),
                            ("MIXED", "Mixed / Co-ed"),
                        ],
                        default="MIXED",
                        max_length=10,
                    ),
                ),
                ("campus", models.CharField(default="Main Campus", max_length=100)),
                ("warden_name", models.CharField(blank=True, max_length=100)),
                ("warden_contact", models.CharField(blank=True, max_length=50)),
                (
                    "rules",
                    models.TextField(
                        blank=True,
                        default="1. Quiet hours from 10 PM to 6 AM.\n2. No unauthorized visitors after 8 PM.\n3. Keep common facilities clean.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostelApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("special_needs", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ALLOCATED", "Allocated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostels.hostel",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_applications",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_applications",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostelBuilding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_floors", models.PositiveSmallIntegerField(default=3)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="hostels.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["hostel", "name"],
                "unique_together": {("hostel", "name")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_number", models.CharField(max_length=20)),
                ("floor", models.PositiveSmallIntegerField(default=1)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Occupancy"),
                            ("DOUBLE", "Double Occupancy"),
                            ("QUAD", "Quad Occupancy (4 Beds)"),
                        ],
                        default="DOUBLE",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostels.hostelbuilding",
                    ),
                ),
            ],
            options={
                "ordering": ["building", "room_number"],
                "unique_together": {("building", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bed_number", models.CharField(max_length=10)),
                ("is_occupied", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("RESERVED", "Reserved"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hostels.room",
                    ),
                ),
            ],
            options={
                "ordering": ["room", "bed_number"],
                "unique_together": {("room", "bed_number")},
            },
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Allocation"),
                            ("TRANSFERRED", "Transferred"),
                            ("TERMINATED", "Terminated / Vacated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                ("vacated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="hostels.bed",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostel_allocations",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allocations",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("bed",),
                        name="unique_active_bed_allocation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("student", "semester"),
                        name="unique_active_student_hostel_per_semester",
                    ),
                ],
            },
        ),
    ]
