# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('campus', models.CharField(default='Main Campus', max_length=100)),
                ('gender_policy', models.CharField(choices=[('MALE', 'Male only'), ('FEMALE', 'Female only'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('gender_policy__in', ['MALE', 'FEMALE', 'MIXED'])), name='hostel_gender_policy_valid')],
            },
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_room_type', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('QUAD', 'Quad')], max_length=10)),
                ('special_needs', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled'), ('ALLOCATED', 'Allocated')], default='SUBMITTED', max_length=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, max_length=2000)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_applications', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_applications', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBuilding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='hostels.hostel')),
            ],
            options={
                'ordering': ['hostel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelFloor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='hostels.hostelbuilding')),
            ],
            options={
                'ordering': ['building', 'level'],
            },
        ),
        migrations.CreateModel(
            name='HostelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='hostels.hostelapplication')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hostels.hostel')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='preferred_hostels',
            field=models.ManyToManyField(related_name='+', through='hostels.HostelPreference', to='hostels.hostel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('QUAD', 'Quad')], default='DOUBLE', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=12)),
                ('fee_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostels.hostelfloor')),
            ],
            options={
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hostels.room')),
            ],
            options={
                'ordering': ['room', 'label'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_ACCEPTANCE', 'Offered, awaiting acceptance'), ('ACTIVE', 'Active'), ('DECLINED', 'Declined'), ('EXPIRED', 'Offer expired'), ('CANCELLED', 'Cancelled'), ('TRANSFERRED', 'Transferred'), ('VACATED', 'Vacated')], default='ACTIVE', max_length=20)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_by', models.ForeignKey(blank=True, help_text='Null when the student booked the bed themselves.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostels.bed')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='accounts.studentprofile')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostels.hostelapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_ACCEPTANCE', 'ACTIVE', 'DECLINED', 'EXPIRED', 'CANCELLED', 'TRANSFERRED', 'VACATED'])), name='hostel_allocation_status_valid'), models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING_ACCEPTANCE', 'ACTIVE'))), fields=('bed', 'semester'), name='allocation_one_holder_per_bed'), models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING_ACCEPTANCE', 'ACTIVE'))), fields=('student', 'semester'), name='allocation_one_bed_per_student')],
            },
        ),
        migrations.CreateModel(
            name='HostelBookingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('APPLICATION', 'Application and allocation'), ('DIRECT_BOOKING', 'Direct booking')], default='DIRECT_BOOKING', max_length=15)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('acceptance_hours', models.PositiveSmallIntegerField(default=48)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_windows', to='academics.semester')),
            ],
            options={
                'ordering': ['-opens_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ['APPLICATION', 'DIRECT_BOOKING'])), name='booking_window_mode_valid'), models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='booking_window_ordered')],
            },
        ),
        migrations.AddConstraint(
            model_name='hostelbuilding',
            constraint=models.UniqueConstraint(fields=('hostel', 'name'), name='building_unique_per_hostel'),
        ),
        migrations.AddConstraint(
            model_name='hostelfloor',
            constraint=models.UniqueConstraint(fields=('building', 'level'), name='floor_unique_per_building'),
        ),
        migrations.AddConstraint(
            model_name='hostelpreference',
            constraint=models.UniqueConstraint(fields=('application', 'rank'), name='hostel_preference_unique_rank'),
        ),
        migrations.AddConstraint(
            model_name='hostelpreference',
            constraint=models.UniqueConstraint(fields=('application', 'hostel'), name='hostel_preference_unique_hostel'),
        ),
        migrations.AddConstraint(
            model_name='hostelpreference',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 3)), name='hostel_preference_rank_range'),
        ),
        migrations.AddConstraint(
            model_name='hostelapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WAITLISTED', 'CANCELLED', 'ALLOCATED'])), name='hostel_application_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='hostelapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REJECTED']), _negated=True), fields=('student', 'semester'), name='hostel_application_one_open_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='room_unique_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('room_type__in', ['SINGLE', 'DOUBLE', 'TRIPLE', 'QUAD'])), name='room_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 8)), name='room_capacity_range'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'MAINTENANCE', 'CLOSED'])), name='room_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('fee_per_semester__gte', 0)), name='room_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='bed_unique_per_room'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'MAINTENANCE', 'CLOSED'])), name='bed_status_valid'),
        ),
    ]
