# Generated by Django 5.2.18 on 2026-10-07 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('clubs', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
                ('audience_roles', models.CharField(choices=[('EVERYONE', 'Everyone'), ('STUDENTS', 'Students'), ('STAFF', 'Staff')], default='EVERYONE', max_length=10)),
                ('scope', models.CharField(choices=[('UNIVERSITY', 'Whole university'), ('FACULTY', 'Faculty'), ('DEPARTMENT', 'Department'), ('PROGRAM', 'Program'), ('OFFERING', 'Unit offering'), ('CLUB', 'Club'), ('INDIVIDUAL', 'Selected individuals')], default='UNIVERSITY', max_length=12)),
                ('publish_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clubs.club')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.faculty')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.unitoffering')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.program')),
                ('recipients', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.announcement')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_attachment', to='core.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REQUEST_STATUS', 'Request status'), ('REQUEST_RESPONSE', 'Request response'), ('HOSTEL', 'Hostel'), ('REGISTRATION', 'Unit registration'), ('TIMETABLE', 'Timetable'), ('CLUB', 'Clubs'), ('ANNOUNCEMENT', 'Announcement'), ('SECURITY', 'Security'), ('SYSTEM', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('route_kwargs', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'publish_at'], name='notificatio_status_5fa055_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('audience_roles__in', ['EVERYONE', 'STUDENTS', 'STAFF'])), name='announcement_audience_valid'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'WITHDRAWN'])), name='announcement_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('publish_at__lt', models.F('expires_at')), _connector='OR'), name='announcement_publish_before_expiry'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope__in', ['UNIVERSITY', 'INDIVIDUAL']), ('club__isnull', True), ('department__isnull', True), ('faculty__isnull', True), ('offering__isnull', True), ('program__isnull', True)), models.Q(('scope', 'FACULTY'), ('club__isnull', True), ('department__isnull', True), ('faculty__isnull', False), ('offering__isnull', True), ('program__isnull', True)), models.Q(('scope', 'DEPARTMENT'), ('club__isnull', True), ('department__isnull', False), ('faculty__isnull', True), ('offering__isnull', True), ('program__isnull', True)), models.Q(('scope', 'PROGRAM'), ('club__isnull', True), ('department__isnull', True), ('faculty__isnull', True), ('offering__isnull', True), ('program__isnull', False)), models.Q(('scope', 'OFFERING'), ('club__isnull', True), ('department__isnull', True), ('faculty__isnull', True), ('offering__isnull', False), ('program__isnull', True)), models.Q(('scope', 'CLUB'), ('club__isnull', False), ('department__isnull', True), ('faculty__isnull', True), ('offering__isnull', True), ('program__isnull', True)), _connector='OR'), name='announcement_scope_target_matches'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='notificatio_recipie_da81fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['REQUEST_STATUS', 'REQUEST_RESPONSE', 'HOSTEL', 'REGISTRATION', 'TIMETABLE', 'CLUB', 'ANNOUNCEMENT', 'SECURITY', 'SYSTEM'])), name='notification_kind_valid'),
        ),
    ]
